apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hongliang001

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  tekton.dev/task: ansible-runner

resources:
  - ansible-deployer.yaml
